[package]
name = "scale"
version = "0.1.0"
authors = ["francesco <fstiffo@sgajo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decimal = "2.0.4"
kairos = "0.3.0"
chrono = "0.4.7"

# cursive = "0.12.0"
